import type { NextPage } from 'next';
import Head from 'next/head';
import Layout from '@components/Layout';
import InstitutionList from '@components/InstitutionList';

const InstitutionsPage: NextPage = () => (
  <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Layout title="Select institution">
      <InstitutionList />
    </Layout>
  </>
);

export default InstitutionsPage;
