import type { NextPage } from 'next';
import Head from 'next/head';
import useAccountAuthorization from '@lib/hooks/useAccountAuthorization';
import useInstitutions from '@lib/hooks/useInstitutions';
import Header from '@components/Header';

const InstitutionsPage: NextPage = () => {
  const { data: institutions } = useInstitutions();
  const { mutate: authorizeAccount } = useAccountAuthorization();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <h1>Select institution</h1>
        <ul>
          {institutions &&
            institutions.map((institution) => (
              <li key={institution.id}>
                <button onClick={() => authorizeAccount(institution.id)}>
                  {institution.fullName}
                </button>
              </li>
            ))}
        </ul>
      </main>
    </div>
  );
};

export default InstitutionsPage;
